name: nacos.io deploy

on:
  push:
    branches:
      - master
      - oss-deploy

jobs:
  Build-Deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Build
        run: |
          mkdir deploy-dist && cp -R zh-cn/ en-us/ build/ img/ md_json/ site_config/ utils/ blog/ deploy-dist/ && mv *.html *.js *.ejs deploy-dist/
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm i @serverless-devs/s -g  --registry=https://registry.npmmirror.com
      - run: s config add --AccountID ${{secrets.ACCOUNT_ID}}  --AccessKeyID ${{secrets.ACCESS_KEYID}}  --AccessKeySecret ${{secrets.ACCESS_KEYSECRET}} -a nacos -f
      - name: Deploy
        run: s deploy --use-local -y
